/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:89e4f18c-0ea1-4a28-bf8b-5fe12dec1bcd",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_C3mzFWsIt",
    "aws_user_pools_web_client_id": "723jvkon3r3eek9hnkjvpts8pc",
    "oauth": {},
    "aws_user_files_s3_bucket": "family-window142315-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
